/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ferreteria;


import vistas.LoginView;

public class App {
   

    public static void main(String[] args) {
      LoginView lv=new LoginView();
      
      lv.setVisible(true);
        
    }
}
